spring:
  datasource:
    url: jdbc:mysql://docker.for.mac.localhost:3308/groupboard
    username: admin
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.ppojin.groupboard.mapper
  mapper-locations: mybatis/mapper/**/*.xml
#  mapper-locations: mybatis/mapper/groupMapper.xml